// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MYDBMISCTBL_H_
#define FLATBUFFERS_GENERATED_MYDBMISCTBL_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

struct MydbMiscInfo;

struct MydbMiscType1Data;
struct MydbMiscType1DataBuilder;

struct MydbMiscType2Data;

struct MydbMiscType3Data;

struct MydbMiscType4Data;

struct MydbMiscTbl;
struct MydbMiscTblBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) MydbMiscInfo FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t id_;
  uint32_t type_;
  uint32_t data_;

 public:
  MydbMiscInfo()
      : id_(0),
        type_(0),
        data_(0) {
  }
  MydbMiscInfo(uint32_t _id, uint32_t _type, uint32_t _data)
      : id_(::flatbuffers::EndianScalar(_id)),
        type_(::flatbuffers::EndianScalar(_type)),
        data_(::flatbuffers::EndianScalar(_data)) {
  }
  uint32_t id() const {
    return ::flatbuffers::EndianScalar(id_);
  }
  uint32_t type() const {
    return ::flatbuffers::EndianScalar(type_);
  }
  uint32_t data() const {
    return ::flatbuffers::EndianScalar(data_);
  }
};
FLATBUFFERS_STRUCT_END(MydbMiscInfo, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) MydbMiscType2Data FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t id_;
  uint32_t field_;

 public:
  MydbMiscType2Data()
      : id_(0),
        field_(0) {
  }
  MydbMiscType2Data(uint32_t _id, uint32_t _field)
      : id_(::flatbuffers::EndianScalar(_id)),
        field_(::flatbuffers::EndianScalar(_field)) {
  }
  uint32_t id() const {
    return ::flatbuffers::EndianScalar(id_);
  }
  uint32_t field() const {
    return ::flatbuffers::EndianScalar(field_);
  }
};
FLATBUFFERS_STRUCT_END(MydbMiscType2Data, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) MydbMiscType3Data FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t id_;
  uint32_t field1_;
  uint32_t field2_;

 public:
  MydbMiscType3Data()
      : id_(0),
        field1_(0),
        field2_(0) {
  }
  MydbMiscType3Data(uint32_t _id, uint32_t _field1, uint32_t _field2)
      : id_(::flatbuffers::EndianScalar(_id)),
        field1_(::flatbuffers::EndianScalar(_field1)),
        field2_(::flatbuffers::EndianScalar(_field2)) {
  }
  uint32_t id() const {
    return ::flatbuffers::EndianScalar(id_);
  }
  uint32_t field1() const {
    return ::flatbuffers::EndianScalar(field1_);
  }
  uint32_t field2() const {
    return ::flatbuffers::EndianScalar(field2_);
  }
};
FLATBUFFERS_STRUCT_END(MydbMiscType3Data, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) MydbMiscType4Data FLATBUFFERS_FINAL_CLASS {
 private:
  uint32_t id_;
  uint32_t field1_;
  uint32_t field2_;
  uint32_t field3_;
  uint32_t field4_;

 public:
  MydbMiscType4Data()
      : id_(0),
        field1_(0),
        field2_(0),
        field3_(0),
        field4_(0) {
  }
  MydbMiscType4Data(uint32_t _id, uint32_t _field1, uint32_t _field2, uint32_t _field3, uint32_t _field4)
      : id_(::flatbuffers::EndianScalar(_id)),
        field1_(::flatbuffers::EndianScalar(_field1)),
        field2_(::flatbuffers::EndianScalar(_field2)),
        field3_(::flatbuffers::EndianScalar(_field3)),
        field4_(::flatbuffers::EndianScalar(_field4)) {
  }
  uint32_t id() const {
    return ::flatbuffers::EndianScalar(id_);
  }
  uint32_t field1() const {
    return ::flatbuffers::EndianScalar(field1_);
  }
  uint32_t field2() const {
    return ::flatbuffers::EndianScalar(field2_);
  }
  uint32_t field3() const {
    return ::flatbuffers::EndianScalar(field3_);
  }
  uint32_t field4() const {
    return ::flatbuffers::EndianScalar(field4_);
  }
};
FLATBUFFERS_STRUCT_END(MydbMiscType4Data, 20);

struct MydbMiscType1Data FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MydbMiscType1DataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_FIELD = 6
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  const ::flatbuffers::String *field() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FIELD);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyOffset(verifier, VT_FIELD) &&
           verifier.VerifyString(field()) &&
           verifier.EndTable();
  }
};

struct MydbMiscType1DataBuilder {
  typedef MydbMiscType1Data Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(MydbMiscType1Data::VT_ID, id, 0);
  }
  void add_field(::flatbuffers::Offset<::flatbuffers::String> field) {
    fbb_.AddOffset(MydbMiscType1Data::VT_FIELD, field);
  }
  explicit MydbMiscType1DataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MydbMiscType1Data> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MydbMiscType1Data>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MydbMiscType1Data> CreateMydbMiscType1Data(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> field = 0) {
  MydbMiscType1DataBuilder builder_(_fbb);
  builder_.add_field(field);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MydbMiscType1Data> CreateMydbMiscType1DataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    const char *field = nullptr) {
  auto field__ = field ? _fbb.CreateString(field) : 0;
  return CreateMydbMiscType1Data(
      _fbb,
      id,
      field__);
}

struct MydbMiscTbl FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MydbMiscTblBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MISC_INFOS = 4,
    VT_TYPE1_DATAS = 6,
    VT_TYPE2_DATAS = 8,
    VT_TYPE3_DATAS = 10,
    VT_TYPE4_DATAS = 12,
    VT___DATE_TIME = 14,
    VT___MAC_ADDRESS = 16
  };
  const ::flatbuffers::Vector<const MydbMiscInfo *> *misc_infos() const {
    return GetPointer<const ::flatbuffers::Vector<const MydbMiscInfo *> *>(VT_MISC_INFOS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<MydbMiscType1Data>> *type1_datas() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MydbMiscType1Data>> *>(VT_TYPE1_DATAS);
  }
  const ::flatbuffers::Vector<const MydbMiscType2Data *> *type2_datas() const {
    return GetPointer<const ::flatbuffers::Vector<const MydbMiscType2Data *> *>(VT_TYPE2_DATAS);
  }
  const ::flatbuffers::Vector<const MydbMiscType3Data *> *type3_datas() const {
    return GetPointer<const ::flatbuffers::Vector<const MydbMiscType3Data *> *>(VT_TYPE3_DATAS);
  }
  const ::flatbuffers::Vector<const MydbMiscType4Data *> *type4_datas() const {
    return GetPointer<const ::flatbuffers::Vector<const MydbMiscType4Data *> *>(VT_TYPE4_DATAS);
  }
  const ::flatbuffers::String *__date_time() const {
    return GetPointer<const ::flatbuffers::String *>(VT___DATE_TIME);
  }
  const ::flatbuffers::String *__mac_address() const {
    return GetPointer<const ::flatbuffers::String *>(VT___MAC_ADDRESS);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MISC_INFOS) &&
           verifier.VerifyVector(misc_infos()) &&
           VerifyOffset(verifier, VT_TYPE1_DATAS) &&
           verifier.VerifyVector(type1_datas()) &&
           verifier.VerifyVectorOfTables(type1_datas()) &&
           VerifyOffset(verifier, VT_TYPE2_DATAS) &&
           verifier.VerifyVector(type2_datas()) &&
           VerifyOffset(verifier, VT_TYPE3_DATAS) &&
           verifier.VerifyVector(type3_datas()) &&
           VerifyOffset(verifier, VT_TYPE4_DATAS) &&
           verifier.VerifyVector(type4_datas()) &&
           VerifyOffset(verifier, VT___DATE_TIME) &&
           verifier.VerifyString(__date_time()) &&
           VerifyOffset(verifier, VT___MAC_ADDRESS) &&
           verifier.VerifyString(__mac_address()) &&
           verifier.EndTable();
  }
};

struct MydbMiscTblBuilder {
  typedef MydbMiscTbl Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_misc_infos(::flatbuffers::Offset<::flatbuffers::Vector<const MydbMiscInfo *>> misc_infos) {
    fbb_.AddOffset(MydbMiscTbl::VT_MISC_INFOS, misc_infos);
  }
  void add_type1_datas(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MydbMiscType1Data>>> type1_datas) {
    fbb_.AddOffset(MydbMiscTbl::VT_TYPE1_DATAS, type1_datas);
  }
  void add_type2_datas(::flatbuffers::Offset<::flatbuffers::Vector<const MydbMiscType2Data *>> type2_datas) {
    fbb_.AddOffset(MydbMiscTbl::VT_TYPE2_DATAS, type2_datas);
  }
  void add_type3_datas(::flatbuffers::Offset<::flatbuffers::Vector<const MydbMiscType3Data *>> type3_datas) {
    fbb_.AddOffset(MydbMiscTbl::VT_TYPE3_DATAS, type3_datas);
  }
  void add_type4_datas(::flatbuffers::Offset<::flatbuffers::Vector<const MydbMiscType4Data *>> type4_datas) {
    fbb_.AddOffset(MydbMiscTbl::VT_TYPE4_DATAS, type4_datas);
  }
  void add___date_time(::flatbuffers::Offset<::flatbuffers::String> __date_time) {
    fbb_.AddOffset(MydbMiscTbl::VT___DATE_TIME, __date_time);
  }
  void add___mac_address(::flatbuffers::Offset<::flatbuffers::String> __mac_address) {
    fbb_.AddOffset(MydbMiscTbl::VT___MAC_ADDRESS, __mac_address);
  }
  explicit MydbMiscTblBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MydbMiscTbl> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MydbMiscTbl>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MydbMiscTbl> CreateMydbMiscTbl(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const MydbMiscInfo *>> misc_infos = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MydbMiscType1Data>>> type1_datas = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const MydbMiscType2Data *>> type2_datas = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const MydbMiscType3Data *>> type3_datas = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const MydbMiscType4Data *>> type4_datas = 0,
    ::flatbuffers::Offset<::flatbuffers::String> __date_time = 0,
    ::flatbuffers::Offset<::flatbuffers::String> __mac_address = 0) {
  MydbMiscTblBuilder builder_(_fbb);
  builder_.add___mac_address(__mac_address);
  builder_.add___date_time(__date_time);
  builder_.add_type4_datas(type4_datas);
  builder_.add_type3_datas(type3_datas);
  builder_.add_type2_datas(type2_datas);
  builder_.add_type1_datas(type1_datas);
  builder_.add_misc_infos(misc_infos);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MydbMiscTbl> CreateMydbMiscTblDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<MydbMiscInfo> *misc_infos = nullptr,
    const std::vector<::flatbuffers::Offset<MydbMiscType1Data>> *type1_datas = nullptr,
    const std::vector<MydbMiscType2Data> *type2_datas = nullptr,
    const std::vector<MydbMiscType3Data> *type3_datas = nullptr,
    const std::vector<MydbMiscType4Data> *type4_datas = nullptr,
    const char *__date_time = nullptr,
    const char *__mac_address = nullptr) {
  auto misc_infos__ = misc_infos ? _fbb.CreateVectorOfStructs<MydbMiscInfo>(*misc_infos) : 0;
  auto type1_datas__ = type1_datas ? _fbb.CreateVector<::flatbuffers::Offset<MydbMiscType1Data>>(*type1_datas) : 0;
  auto type2_datas__ = type2_datas ? _fbb.CreateVectorOfStructs<MydbMiscType2Data>(*type2_datas) : 0;
  auto type3_datas__ = type3_datas ? _fbb.CreateVectorOfStructs<MydbMiscType3Data>(*type3_datas) : 0;
  auto type4_datas__ = type4_datas ? _fbb.CreateVectorOfStructs<MydbMiscType4Data>(*type4_datas) : 0;
  auto __date_time__ = __date_time ? _fbb.CreateString(__date_time) : 0;
  auto __mac_address__ = __mac_address ? _fbb.CreateString(__mac_address) : 0;
  return CreateMydbMiscTbl(
      _fbb,
      misc_infos__,
      type1_datas__,
      type2_datas__,
      type3_datas__,
      type4_datas__,
      __date_time__,
      __mac_address__);
}

inline const MydbMiscTbl *GetMydbMiscTbl(const void *buf) {
  return ::flatbuffers::GetRoot<MydbMiscTbl>(buf);
}

inline const MydbMiscTbl *GetSizePrefixedMydbMiscTbl(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<MydbMiscTbl>(buf);
}

template <bool B = false>
inline bool VerifyMydbMiscTblBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<MydbMiscTbl>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMydbMiscTblBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<MydbMiscTbl>(nullptr);
}

inline void FinishMydbMiscTblBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MydbMiscTbl> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMydbMiscTblBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MydbMiscTbl> root) {
  fbb.FinishSizePrefixed(root);
}

#endif  // FLATBUFFERS_GENERATED_MYDBMISCTBL_H_
